// This file is autogenerated. Changes will be overwritten.
#include <4TFUULJ3UP/moc_KTXCache.cpp>
#include <4TFUULJ3UP/moc_ModelCache.cpp>
#include <4TFUULJ3UP/moc_ModelCacheScriptingInterface.cpp>
#include <4TFUULJ3UP/moc_TextureCache.cpp>
#include <4TFUULJ3UP/moc_TextureCacheScriptingInterface.cpp>
