// This file is autogenerated. Changes will be overwritten.
#include <UVLADIE3JM/moc_Baker.cpp>
#include <UVLADIE3JM/moc_FBXBaker.cpp>
#include <UVLADIE3JM/moc_JSBaker.cpp>
#include <UVLADIE3JM/moc_ModelBaker.cpp>
#include <UVLADIE3JM/moc_OBJBaker.cpp>
#include <UVLADIE3JM/moc_TextureBaker.cpp>
