// This file is autogenerated. Changes will be overwritten.
#include <UVLADIE3JM/moc_AvatarData.cpp>
#include <UVLADIE3JM/moc_AvatarHashMap.cpp>
#include <UVLADIE3JM/moc_ClientTraitsHandler.cpp>
#include <UVLADIE3JM/moc_ScriptAvatarData.cpp>
