// This file is autogenerated. Changes will be overwritten.
#include <6RKTIGWZ46/moc_KeyboardMouseDevice.cpp>
#include <6RKTIGWZ46/moc_TouchscreenDevice.cpp>
#include <6RKTIGWZ46/moc_TouchscreenVirtualPadDevice.cpp>
