// This file is autogenerated. Changes will be overwritten.
#include <EDHBGAVMLL/moc_AbstractLoggerInterface.cpp>
#include <EDHBGAVMLL/moc_Camera.cpp>
#include <EDHBGAVMLL/moc_FileCache.cpp>
#include <EDHBGAVMLL/moc_FileLogger.cpp>
#include <EDHBGAVMLL/moc_MiniPromises.cpp>
#include <EDHBGAVMLL/moc_ScriptInitializerMixin.cpp>
#include <UVLADIE3JM/moc_BaseScriptEngine.cpp>
#include <UVLADIE3JM/moc_DebugDraw.cpp>
#include <UVLADIE3JM/moc_GenericThread.cpp>
#include <UVLADIE3JM/moc_LogHandler.cpp>
#include <UVLADIE3JM/moc_PathUtils.cpp>
#include <UVLADIE3JM/moc_Preferences.cpp>
#include <UVLADIE3JM/moc_RegisteredMetaTypes.cpp>
#include <UVLADIE3JM/moc_ResourceRequestObserver.cpp>
#include <UVLADIE3JM/moc_SettingManager.cpp>
#include <UVLADIE3JM/moc_ShutdownEventListener.cpp>
