// This file is autogenerated. Changes will be overwritten.
#include <AT4DJUVEOG/moc_RegionState.cpp>
#include <AT4DJUVEOG/moc_RegionTracker.cpp>
#include <AT4DJUVEOG/moc_SpaceClassifier.cpp>
#include <AT4DJUVEOG/moc_ViewTask.cpp>
