// This file is autogenerated. Changes will be overwritten.
#include <UVLADIE3JM/moc_HTTPConnection.cpp>
#include <UVLADIE3JM/moc_HTTPManager.cpp>
#include <UVLADIE3JM/moc_HTTPSConnection.cpp>
#include <UVLADIE3JM/moc_HTTPSManager.cpp>
