// This file is autogenerated. Changes will be overwritten.
#include <UVLADIE3JM/moc_AbstractAudioInterface.cpp>
#include <UVLADIE3JM/moc_AudioEffectOptions.cpp>
#include <UVLADIE3JM/moc_AudioInjector.cpp>
#include <UVLADIE3JM/moc_AudioInjectorLocalBuffer.cpp>
#include <UVLADIE3JM/moc_AudioInjectorManager.cpp>
#include <UVLADIE3JM/moc_InboundAudioStream.cpp>
#include <UVLADIE3JM/moc_MixedProcessedAudioStream.cpp>
#include <UVLADIE3JM/moc_PositionalAudioStream.cpp>
#include <UVLADIE3JM/moc_Sound.cpp>
#include <UVLADIE3JM/moc_SoundCache.cpp>
#include <UVLADIE3JM/moc_SoundCacheScriptingInterface.cpp>
